#!/bin/bash
echo 'Building...'

rm -rf builds
mkdir builds

cp -rf scene-opium scene-opium.wdgt
cp -rf shared/* scene-opium.wdgt
cp -rf scene-ioannina scene-ioannina.wdgt
cp -rf shared/* scene-ioannina.wdgt
cp -rf scene-luis scene-luis.wdgt
cp -rf shared/* scene-luis.wdgt
cp -rf scene-ishi scene-ishi.wdgt
cp -rf shared/* scene-ishi.wdgt
cp -rf scene-william scene-william.wdgt
cp -rf shared/* scene-william.wdgt
cp -rf scene-jonas scene-jonas.wdgt
cp -rf shared/* scene-jonas.wdgt
cp -rf scene-arun scene-arun.wdgt
cp -rf shared/* scene-arun.wdgt

cp -rf documents/opium document-opium.wdgt
cp -rf documents/_shared/* document-opium.wdgt
cp -rf documents/ioannina document-ioannina.wdgt
cp -rf documents/_shared/* document-ioannina.wdgt
cp -rf documents/luis document-luis.wdgt
cp -rf documents/_shared/* document-luis.wdgt
cp -rf documents/ishi document-ishi.wdgt
cp -rf documents/_shared/* document-ishi.wdgt
cp -rf documents/william document-william.wdgt
cp -rf documents/_shared/* document-william.wdgt
cp -rf documents/jonas document-jonas.wdgt
cp -rf documents/_shared/* document-jonas.wdgt
cp -rf documents/arun document-arun.wdgt
cp -rf documents/_shared/* document-arun.wdgt
cp -rf documents/RiseFallOttomans sequence-ioannina.wdgt
cp -rf documents/_shared/* sequence-ioannina.wdgt


zip -r scene-opium.zip scene-opium.wdgt
zip -r scene-ioannina.zip scene-ioannina.wdgt
zip -r scene-luis.zip scene-luis.wdgt
zip -r scene-ishi.zip scene-ishi.wdgt
zip -r scene-william.zip scene-william.wdgt
zip -r scene-jonas.zip scene-jonas.wdgt
zip -r scene-arun.zip scene-arun.wdgt


zip -r document-opium.zip document-opium.wdgt
zip -r document-ioannina.zip document-ioannina.wdgt
zip -r document-luis.zip document-luis.wdgt
zip -r document-ishi.zip document-ishi.wdgt
zip -r document-william.zip document-william.wdgt
zip -r document-jonas.zip document-jonas.wdgt
zip -r document-arun.zip document-arun.wdgt
zip -r sequence-ioannina.zip sequence-ioannina.wdgt

mv scene-opium.zip ./builds
mv scene-ioannina.zip ./builds
mv scene-luis.zip ./builds
mv scene-ishi.zip ./builds
mv scene-william.zip ./builds
mv scene-jonas.zip ./builds
mv scene-arun.zip ./builds

mv document-opium.zip ./builds
mv document-ioannina.zip ./builds
mv document-luis.zip ./builds
mv document-ishi.zip ./builds
mv document-william.zip ./builds
mv document-jonas.zip ./builds
mv document-arun.zip ./builds
mv sequence-ioannina.zip ./builds

rm -rf scene-opium.wdgt
rm -rf scene-ioannina.wdgt
rm -rf scene-luis.wdgt
rm -rf scene-ishi.wdgt
rm -rf scene-william.wdgt
rm -rf scene-jonas.wdgt
rm -rf scene-arun.wdgt

rm -rf document-opium.wdgt
rm -rf document-ioannina.wdgt
rm -rf document-luis.wdgt
rm -rf document-ishi.wdgt
rm -rf document-william.wdgt
rm -rf document-jonas.wdgt
rm -rf document-arun.wdgt
rm -rf sequence-ioannina.wdgt
