#!/bin/bash
echo 'Building...'

# clean up build folder
rm -rf builds
mkdir builds

function zipMoveCleanUp {
    # compress asset for web download
    zip -r $1.zip $1.wdgt

    # move into builds directory
    mv $1.zip ./builds

    # clean up directories used for build
    rm -rf $1.wdgt
}

# creates all scenes
allScenes=("scene-opium" "scene-ioannina" "scene-luis" "scene-ishi" "scene-william" "scene-jonas" "scene-arun" "scene-agent-v1" "scene-chicago-v1" "scene-jemba-v1" "scene-khari-v1")
for name in ${allScenes[@]}; do
    # copy scene source and shared files in one wdgt folder
    cp -rf ${name} ${name}.wdgt
    cp -rf shared/* ${name}.wdgt

    zipMoveCleanUp ${name}
done

# creates all documents
allDocuments=("opium" "ioannina" "luis" "ishi" "william" "jonas" "arun" "agent" "chicago" "jemba" "khari")
for name in ${allDocuments[@]}; do
    # copy documents source and shared files in one wdgt folder
    cp -rf documents/${name} document-${name}.wdgt
    cp -rf documents/_shared/* document-${name}.wdgt

    zipMoveCleanUp document-${name}
done

# creates all sequences
allSequences=("RiseFallOttomans" "5routes" "MughalEmpire" "TriangularTrade" "beforeAfter" "BlackbeardsBeauty")
for name in ${allSequences[@]}; do
    # copy sequence source and shared files in one wdgt folder
    cp -rf documents/${name} sequence-${name}.wdgt

    zipMoveCleanUp sequence-${name}
done

# creates all quizes
allQuizes=("ioannina" "luis" "ishi" "william" "jonas" "arun" "agent" "chicago" "jemba" "khari" "opium")
for name in ${allQuizes[@]}; do
    # copy quiz source and shared files in one wdgt folder
    cp -rf quiz/${name} quiz-${name}.wdgt
    cp -rf quiz/_shared/* quiz-${name}.wdgt
    cp -rf shared/* quiz-${name}.wdgt

    zipMoveCleanUp quiz-${name}
done

cp index-prod.html builds/index.html

# uploads to server
scp -r ./builds root@134.122.29.44:/srv/www/ibooks.web
# unzip in server
ssh root@134.122.29.44 '/srv/www/ibooks.web/build'

# notify telegram
curl -X GET -G \
'https://api.telegram.org/bot1398011287:AAHZ-K64-wDkKczULH8NjXa-8d_-SrCLrD8/sendMessage' \
-d chat_id='-462876348' \
-d text="deploy completed by `whoami`" \
